service:
  name: auction-service

# serverless-pseudo-parameters plugins is used to access AWS metadata
# e.x - #{AWS::Region}, #{AWS::AccountId}
plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  # environment variable defined in provider is accessible to application
  # environment variable defined in functions is accessible to that function only
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    AUCTIONS_BUCKET_NAME: ${self:custom.AuctionsBucket.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    AUCTIONS_START_QUEUE_URL: ${self:custom.AuctionStartQueue.url}
    AUCTION_TOPIC_ARN: ${self:custom.AuctionTopic.arn}
  # iamRoleStaments is the array of object
  # here we have given path of the AuctionsTableIAM rule file
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    - ${file(iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
      Resources: ${self:custom.AuctionStartQueue.arn}
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
      Resources: ${self:custom.MailQueue.arn}
    - Effect: Allow
      Action:
        - sns:Publish
      Resources: ${self:custom.AuctionTopic.arn}

resources:
  Resources:
    # this Resources follows cloud formation sytax
    # it contains objects of resources
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket: ${file(resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(resources/AuctionsBucket.yml):AuctionsBucketPolicy}

    # __________________________________________________
    AuctionTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: AuctionStart-${self:provider.stage}
        Subscription:
          - Endpoint: ${self:custom.MailQueue.arn}
            Protocol: sqs

    AuctionStartQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.AuctionStartQueue.name}
        FifoQueue: true
    # policy allows SNS to publish to SQS queue 
    SnsToSQSPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: AuctionStartQueue
        PolicyDocument:
          Statement:
            - Sid: "Allow SNS publish to SQS"
              Effect: Allow
              Principal: '*'
              Action: sqs:SendMessage
              Resources: ${self:custom.AuctionStartQueue.arn}
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref AuctionTopic
    # __________________________________________________
    
    MailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.MailQueue.name}
        FifoQueue: true

  
  # Outputs:
  #   MailQueueArn:
  #     Value: ${self:custom.MailQueue.arn}
  #     Export:
  #       Name: ${self:custom.MailQueue.name}-Arn
  #   MailQueueUrl:
  #     Value: ${self:custom.MailQueue.url}
  #     Export:
  #       Name: ${self:custom.MailQueue.name}-Url


functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auctions/{id}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid

  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events:
    # # schedule is going to use AWS event bridge
    # # It is a service that helps in scheduling events
    # # you can use cron syntax or can use rate
    #   - schedule: rate(1 minute)

  # lambda function to upload picture to S3 bucket
  uploadAuctionPicture:
    handler: src/handlers/uploadAuctionPicture.handler
    events:
      - https:
          methods: PATCH
          path: auction/{id}/picture

  # lambda function to be triggered whenever a new object is created
  # in s3 bucket
  uploadHandler:
    handler: src/handlers/uploadHandler.handler
    events:
      - s3:
          bucket: ${self:custom.AuctionsBucket.name}
          event: s3:ObjectCreated:*

  # recieves the message from AuctionStartQueue
  # AuctionStartQueue recieves the message from AuctionTopic sns
  notifyAuctionStarted:
    handler: src/handlers/notifyAuctionStarted.handler
    events:
      - sqs:
          arn: ${self:custom.AuctionStartQueue.arn}
          batchSize: 1

  # recieves the message from MailQueue
  notifyAuctionEnded:
    handler: src/handlers/notifyAuctionEnded.handler
    events:
      - sqs:
          arn: ${self:custom.MailQueue.arn}
          # default batch size is 10 and it is also max
          batchSize: 1


# !Ref AuctionsTable will be replaced by table name
# !GetAtt AuctionsTable.Arn will be replaced by arn
# e.x AuctionsTable.name = AuctionsTable-dev or AuctionsTable-stage
# AuctionsTable.Arn = arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/AuctionTable
custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  # Amazon S3 bucket is global.
  # there are not region specific.
  # as buckets are global name should be unique across entire AWS platform
  # name should be in lowercase
  AuctionsBucket:
    name: auctions-bucket-4nj454-${self:provider.stage}

  AuctionStartQueue:
    arn: !GetAtt AuctionStartQueue.Arn
    url: !GetAtt AuctionStartQueue.Url

  AuctionTopic:
    arn: !GetAtt AuctionTopic.Arn
    url: !GetAtt AuctionTopic.Url

  MailQueue:
  # arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn}
  # url: ${cf:notification-service-${self:provider.stage}.MailQueueUrl}
  arn: !GetAtt MailQueue.Arn
  url: !GetAtt MailQueue.Url
