AuctionsBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.AuctionsBucket.name}
    # removes file after one day
    # LifeCycleConfiguration:
    #   Rules:
    #     - Id: ExpirePictures
    #       Status: Enabled
    #       ExpirationInDays: 1

AuctionsBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref AuctionsBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          # here bucket is globaal that's why we are not passing region
          Resources: arn:aws:s3:::${self:custom.AuctionsBucket.name}/*